const GuiText = {
  "Arabic": {
    "textConverterTab": "محول النصوص",
    "tableEditorTab": "محرر الجداول",
    "filetranslatorTab": "مترجم الملفات",
    "extractor&enterorTab": "المدخل والمستخرج",
    "aboutTab": "عني",
    "incharsCount": "الحر(و)ف [",
    "outcharsCount": "الحر(و)ف [",
    "convertbutton": "تحويل النص",
    "drawresulttextbutton": "رسم النص الخارج",
    "loadfilebutton": "فتح ملف",
    "suggestDTEs": "اقترح اختزالات",
    "dialogbox": "متصفحك لا يدعم تعليمة (canvas).",
    "textconvertings": "تحويلات النص:",
    "freezelabel": "جمّده",
    "unfreezelabel": "انقض تجميده",
    "cipherlabel": "رمّزه",
    "uncipherlabel": "انقض ترميزه",
    "reversealllabel": "اعكسه",
    "reversearabilabel": "اعكس العربية فيه",
    "compresslabel": "اختزله",
    "uncompresslabel": "انقض اختزاله",
    "extractlabel": "استخرج منه",
    "putinboxlabel": "ضعه في صندوق",
    "harakatconvertings": "تحويلات الحركات:",
    "delharakatlabel": "احذفها",
    "mergeharakatlabel": "ادمجها",
    "offsetharakatlabel": "أزحها",
    "keepfirstharakatlabel": "أبق الأولى بالتتالي",
    "connectharakatlabel": "ضع لها تطويلة",
    "extractingpatternlabel": "تعبير الاستخراج:",
    "commandspatternlabel": "تعبير الأوامر:",
    "inbytepatternlabel": "تعبير البايت الداخل:",
    "outbytepatternlabel": "تعبير البايت الخارج:",
    "textoffsetpatternlabel": "تعبير إزاحة النص:",
    "linecomlabel": "أمر السطر:",
    "pagecomlabel": "أمر الصفحة:",
    "defaultcharlabel": "الرمز الافتراضي:",
    "harakatoffsetlabel": "إزاحة الحركات بـ:",
    "dtesnumlabel": "عدد الاختزالات:",
    "dteslenslabel": "أطوال الاختزالات:",
    "useddteslabel": "الاختزالات المستعملة:",
    "fontsizelabel": "حجم الخط:",
    "boxsizelabel": "حجم صندوق الخط:",
    "pxbetweenlineslabel": "بين سطور الصندوق:",
    "convertfromlabel": "تحويل من:",
    "normaltextoption": "الأشكال الطباعية",
    "inbytepatternoption": "تعبير البايت الداخل",
    "converttolabel": "إلى:",
    "normaltextoption2": "الأشكال الطباعية",
    "outbytepatternoption": "تعبير البايت الداخل",
    "textoffsetlabel": "إزاحة النص:",
    "leavetextoffsetoption": "اتركه على حاله",
    "textfirstoption": "النص في البداية واملأ ما بعده",
    "textlastoption": "النص في النهاية واملأ ما قبله",
    "textmiddleoption": "النص في الوسط واملأ ما قبله",
    "textmiddlefilledoption": "النص في الوسط واملأ ما قبله وبعده",
    "textoffsetwithlabel": "بـ:",
    "textoffsetwithspacesoption": "الفراغات",
    "textoffsetwithcomoption": "تعبير إزاحة النص",
    "notinciphertablelabel": "المفقود من الترميز:",
    "leavenotincipheroption": "يترك على حاله",
    "replacewithdefaultcipheroption": "يعوض بالرمز الافتراضي",
    "delcipheroption": "يحذف",
    "otherconvertingscriptslabel": "سكربتات تحويل:",
    "rtlboxlabel": "سريان من اليمين",
    "autoconvertlabel": "تحويل تلقائي",
    "autocopylabel": "نسخ تلقائي",
    "chipertablebutton": "فتح جدول ترميز",
    "openfontbutton": "فتح خط",
	"ctetitle": "- محرر جداول الترميز -",
	"loadcipheringtable": "فتح جدول",
	"savecipheringtableacttbl": "حفظ الجدول act",
	"savecipheringtabletbltbl": "حفظ الجدول tbl",
	"fnttablecreatortitle": "- منتج جداول fnt -",
	"afftablecreatortitle": "- منتج جداول aff -",
	"filetranslatortextpattern": "تعبير النص:",
	"filetranslatortranslationpattern": "تعبير الترجمة:",
	"filetranslatorloadfile": "فتح ملف",
	"filetranslatorsavefile": "حفظ الملف",
	"about": "<b>صنع هذه الأداة: <a href='https://github.com/asgore-undertale' target='_blank'>آسغور</a>.<br>وشكر خاص للأخ <a href='https://twitter.com/MansourSorosoro' target='_blank'>منصور</a> لتقديمه معظم أفكار الأداة.<br><a href='https://github.com/asgore-undertale/RenovArabi' target='_blank'>رابط الأداة.</a><br><br>معلومات مهمة:<br>|- تأكد من فتح الكونسول.<br>|- التجميد تلقائي عند التجميد والاختزال لكن ليس عند نقضهما.<br>|- ترتيب عمليات التحويل:<br>|-- + الاستخراج.<br>|-- + تحويل البايتات لنص.<br>|-- + حذف الحركات.<br>|-- + دمج الحركات.<br>|-- + إزاحة الحركات.<br>|-- + إبقاء أول حركة.<br>|-- + إضافة تطويلة للحركات.<br>|-- + التجميد.<br>|-- + الاختزال.<br>|-- + عكس النص كاملاً.<br>|-- + عكس العربية.<br>|-- + ترميز.<br>|-- + نقض الترميز.<br>|-- + نقض الاختزال.<br>|-- + نقض التجميد.<br>|-- + تحويل النص لبايتات.<br>|-- + وضع النص في صندوق.<br>|-- + إزاحة النص.<br></b>",
  },
  "English": {
    "textConverterTab": "Text Converter",
    "tableEditorTab": "Table Editor",
    "filetranslatorTab": "Files Translator",
    "extractor&enterorTab": "Extractor & Enteror",
    "aboutTab": "About",
    "incharsCount": "char(s) [",
    "outcharsCount": "char(s) [",
    "convertbutton": "Convert text",
    "drawresulttextbutton": "Draw resulting text",
    "loadfilebutton": "Load file",
    "suggestDTEs": "Suggest DTEs",
    "dialogbox": "You browser does not support (canvas).",
    "textconvertings": "Text Convertings:",
    "freezelabel": "Freeze it",
    "unfreezelabel": "Unfreeze it",
    "cipherlabel": "Chiper it",
    "uncipherlabel": "Unchiper it",
    "reversealllabel": "Reverse it",
    "reversearabilabel": "Reverse Arabic",
    "compresslabel": "Compress it",
    "uncompresslabel": "Uncompress it",
    "extractlabel": "Extract from it",
    "putinboxlabel": "Put it in a box",
    "harakatconvertings": "Harakat Convertings:",
    "delharakatlabel": "Delete them",
    "mergeharakatlabel": "Merg them",
    "offsetharakatlabel": "Offset them",
    "keepfirstharakatlabel": "Keep first when cascaded",
    "connectharakatlabel": "Convert them to middle form",
    "extractingpatternlabel": "Extracting pattern:",
    "commandspatternlabel": "Commands pattern:",
    "inbytepatternlabel": "Entered byte pattern:",
    "outbytepatternlabel": "Resulting byte pattern:",
    "textoffsetpatternlabel": "Text offseting pattern:",
    "linecomlabel": "Line command:",
    "pagecomlabel": "Page command:",
    "defaultcharlabel": "Default letter:",
    "harakatoffsetlabel": "Offset harakat by:",
    "dtesnumlabel": "Number of dtes:",
    "dteslenslabel": "Lengths of dtes:",
    "useddteslabel": "Used dtes:",
    "fontsizelabel": "Font size:",
    "boxsizelabel": "Dialogbox size:",
    "pxbetweenlineslabel": "Pixels between lines:",
    "convertfromlabel": "Convert from:",
    "normaltextoption": "Normal text",
    "inbytepatternoption": "Entered byte pattern",
    "converttolabel": "To:",
    "normaltextoption2": "Normal text",
    "outbytepatternoption": "Resulting byte pattern",
    "textoffsetlabel": "Text offset:",
    "leavetextoffsetoption": "Leave it be",
    "textfirstoption": "Text first and fill after it",
    "textlastoption": "Text last and fill before it",
    "textmiddleoption": "Text in middle and fill before it",
    "textmiddlefilledoption": "Text in middle and fill before and after it",
    "textoffsetwithlabel": "With:",
    "textoffsetwithspacesoption": "Spaces",
    "textoffsetwithcomoption": "Text offset commands",
    "notinciphertablelabel": "Not in ciphering table:",
    "leavenotincipheroption": "Leave it be",
    "replacewithdefaultcipheroption": "Replace it with the default letter",
    "delcipheroption": "Delete it",
    "otherconvertingscriptslabel": "Other converting scripts:",
    "rtlboxlabel": "RTL box",
    "autoconvertlabel": "Auto convert",
    "autocopylabel": "Auto copy",
    "chipertablebutton": "Load ciphering table",
    "openfontbutton": "Load font",
	"ctetitle": "- Ciphering Table Editor -",
	"loadcipheringtable": "Load table",
	"savecipheringtableacttbl": "Save table as .act",
	"savecipheringtabletbltbl": "Save table as .tbl",
	"fnttablecreatortitle": "- fnt Table Creator -",
	"afftablecreatortitle": "- aff Table Creator -",
	"filetranslatortextpattern": "text pattern:",
	"filetranslatortranslationpattern": "translation pattern:",
	"filetranslatorloadfile": "Load file",
	"filetranslatorsavefile": "Save file",
	"about": "<b>This tool was made by: <a href='https://github.com/asgore-undertale' target='_blank'>Asgore</a>.<br>And special thanks to <a href='https://twitter.com/MansourSorosoro' target='_blank'>Mansour</a> for his great ideas.<br><a href='https://github.com/asgore-undertale/RenovArabi' target='_blank'>Link of the tool.</a><br><br>Important info:<br>|- Make sure to check the console.<br>|- Freezing is automatically applied when ciphering and compressing text but not when unciphering and uncompressing.<br>|- The order of converting steps:<br>|-- + Extracting.<br>|-- + Converting from bytes.<br>|-- + Harakat deleting.<br>|-- + Harakat merging.<br>|-- + Harakat offseting.<br>|-- + Keeping first haraka.<br>|-- + Converting harakat to middle form.<br>|-- + Freezing.<br>|-- + Compressing.<br>|-- + Reversing whole text.<br>|-- + Reversing Arabic.<br>|-- + Ciphering.<br>|-- + Unciphering.<br>|-- + Uncompressing.<br>|-- + Unfreezing.<br>|-- + Converting to bytes.<br>|-- + Putting text in box.<br>|-- + Offseting text.<br></b>",
  }
}